### ISSUE TITLE
Floating point exception(core dumped) error at sim$get_samples_forest

### ISSUE THREAD

**Issue by riccardobergamin** [caravagnalab/rRACES#89] opened 2024-03-09 17:03 UTC
I am running the following script on ORFEO:

```{r}
 easypar_generated_function = function (j) 
{
    library(rRACES)
    library(ggplot2)
    library(dplyr)
    library(ggpubr)
    library(pbapply)
    library(easypar)
    setwd("/orfeo/scratch/cdslab/rbergamin/races")
    source("R/homogeneous_visualization.R")
    g = expand.grid(rp = c(7e-04, 0.001, 0.005, 0.01, 0.05), 
        s = c(0, 0.3, 0.7, 1, 1.5)) %>% as_tibble() %>% mutate(rn = rp, 
        lambda_n = 1) %>% mutate(lambda_p = lambda_n * (1 + s))
    rn = g[j, ]$rn
    rp = g[j, ]$rp
    lambda_p = g[j, ]$lambda_p
    lambda_n = g[j, ]$lambda_n
    label = "gradient_s_r"
    starting_cell = "A-"
    dir.create(paste0("homogeneous_test/epigenetic/", label))
    dir.create(paste0("homogeneous_test/epigenetic/", label, 
        "/", j))
    dir.create(paste0("homogeneous_test/epigenetic/", label, 
        "/", j, "/forest"))
    statistics = lapply(1:50, FUN = function(k) {
        Nn = 0
        Np = 0
        while (Nn == 0 | Np == 0) {
            tryCatch({
                sim <- new(Simulation, paste0("homogeneous_test/epigenetic/", 
                  label, "/", j, "/sims/", k), seed = sample(x = 1:10000, 
                  size = 1), save_snapshot = F)
                sim$duplicate_internal_cells <- T
                sim$update_tissue("Liver", 2000, 2000)
                sim$add_mutant(name = "A", epigenetic_rates = c(`+-` = rn, 
                  `-+` = rp), growth_rates = c(`+` = lambda_p, 
                  `-` = lambda_n), death_rates = c(`+` = 0, `-` = 0))
                sim$place_cell(starting_cell, 1000, 1000)
                sim$run_up_to_size(ifelse(starting_cell == "A-", 
                  "A+", "A-"), 10000)
                n_w <- n_h <- 50
                bbox <- sim$search_sample(c(`A+` = 50, `A-` = 50), 
                  n_w, n_h)
                sim$sample_cells("Sampling", bbox$lower_corner, 
                  bbox$upper_corner)
                forest <- sim$get_samples_forest()
                Ntot = forest$get_nodes() %>% filter(is.na(sample)) %>% 
                  group_by(epistate) %>% summarize(n = length(cell_id))
                Nn = Ntot %>% filter(epistate == "-") %>% pull(n)
                Np = Ntot %>% filter(epistate == "+") %>% pull(n)
                if (length(Nn) == 0) {
                  Nn = 0
                }
                if (length(Np) == 0) {
                  Np = 0
                }
                ccfn = Nn/(Nn + Np)
                ccfp = 1 - ccfn
            }, error = function(cond) {
                message(paste("rRACES error : Wrong cell file format"))
            })
        }
        ancestor_table = get_ancestor_table(forest)
        switching_times = get_switching_times(ancestor_table)
        switch_branches = get_switch_branches(switching_times, 
            forest)
        claid_table = get_epi_claids(switch_branches, ancestor_table)
        forest$save(paste0("homogeneous_test/epigenetic/", label, 
            "/", j, "/forest/forest_", k, ".sff"))
        saveRDS(claid_table, file = paste0("homogeneous_test/epigenetic/", 
            label, "/", j, "/forest/claid_table_", k, ".rds"))
        return(claid_table %>% mutate(sample = k, lambda_n = lambda_n, 
            lambda_p = lambda_p, rn = rn, rp = rp, label = label, 
            starting_cell = starting_cell))
    }) %>% bind_rows()
    dir.create(paste0("homogeneous_test/epigenetic/", label, 
        "/", j, "/stats"))
    saveRDS(statistics, file = paste0("homogeneous_test/epigenetic/", 
        label, "/", j, "/stats/claid_table.rds"))
} 

if(sys.nframe() == 0L) {
   args = commandArgs(trailingOnly = TRUE)
   j = args[1]
print("\nInput parameters for the function\n")
   print(j)
   easypar_generated_function(j)
}
```

I am getting the error: 
```{bash}
/var/spool/slurm/d/job378965/slurm_script: line 38: 2583706 Floating point exception(core dumped) Rscript $R_script $j
```

This happens at the command `forest <- sim$get_samples_forest()`.

i attach useful files for running the job
[folder.zip](https://github.com/caravagnalab/rRACES/files/14547153/folder.zip)

**Comment by albertocasagrande** [comment] 2024-03-09 17:21
Can you provide a simplier example? The script seed is randomly selected can you deterministically choose a seed that produces the exception? What slurm command do you use?

**Comment by riccardobergamin** [comment] 2024-03-09 17:53
yes, sure. I am trying with fixed seed. The command is  "sbatch   path/EASYPAR_LSF_submission.sh" . I upload the sh file in the zip.

**Comment by riccardobergamin** [comment] 2024-03-09 17:58
` 
my_function = function(j){
library(rRACES)
    library(ggplot2)
    library(dplyr)
    library(ggpubr)
    library(easypar)
    setwd("/orfeo/scratch/cdslab/rbergamin/races")
    g = expand.grid(rp = c(7e-04, 0.001, 0.005, 0.01, 0.05), 
        s = c(0, 0.3, 0.7, 1, 1.5)) %>% as_tibble() %>% mutate(rn = rp, 
        lambda_n = 1) %>% mutate(lambda_p = lambda_n * (1 + s))
     rn = g[j, ]$rn
    rp = g[j, ]$rp
    lambda_p = g[j, ]$lambda_p
    lambda_n = g[j, ]$lambda_n
    label = "gradient_s_r"
    starting_cell = "A-"
    dir.create(paste0("homogeneous_test/epigenetic/", label))
    dir.create(paste0("homogeneous_test/epigenetic/", label, 
        "/", j))
    dir.create(paste0("homogeneous_test/epigenetic/", label, 
        "/", j, "/forest"))
    statistics = lapply(1:50, FUN = function(k) {
        Nn = 0
        Np = 0
        while (Nn == 0 | Np == 0) {
            tryCatch({
                sim <- new(Simulation, paste0("homogeneous_test/epigenetic/", 
                  label, "/", j, "/sims/", k), seed = k, save_snapshot = F)
                sim$duplicate_internal_cells <- T
                sim$update_tissue("Liver", 2000, 2000)
                sim$add_mutant(name = "A", epigenetic_rates = c(`+-` = rn, 
                  `-+` = rp), growth_rates = c(`+` = lambda_p, 
                  `-` = lambda_n), death_rates = c(`+` = 0, `-` = 0))
                sim$place_cell(starting_cell, 1000, 1000)
                sim$run_up_to_size(ifelse(starting_cell == "A-", 
                  "A+", "A-"), 10000)
                n_w <- n_h <- 50
                bbox <- sim$search_sample(c(`A+` = 50, `A-` = 50), 
                  n_w, n_h)
                sim$sample_cells("Sampling", bbox$lower_corner, 
                  bbox$upper_corner)
                forest <- sim$get_samples_forest(). 
}`

You got the error for j = 3, k = 1, seed = 1.

**Comment by albertocasagrande** [comment] 2024-03-11 07:19
I was not able to execute above script: I get 

```
Error: unexpected symbol in:
"                  bbox$upper_corner)
                forest <- sim$get_samples_forest()."
Execution halted
```

**Comment by riccardobergamin** [comment] 2024-03-12 09:15
isn't  

sim$sample_cells("Sampling", bbox$lower_corner, 
                  bbox$upper_corner)


the command for sampling?

**Comment by albertocasagrande** [comment] 2024-03-12 10:22
Did you try to execute the code in your second last comment?

**Comment by riccardobergamin** [comment] 2024-03-13 11:36
i tried to run the following:

`j = 3

  library(rRACES)
  library(ggplot2)
  library(dplyr)
  library(ggpubr)
  library(easypar)
  
  g = expand.grid(rp = c(7e-04, 0.001, 0.005, 0.01, 0.05), 
                  s = c(0, 0.3, 0.7, 1, 1.5)) %>% as_tibble() %>% mutate(rn = rp, 
                                                                         lambda_n = 1) %>% mutate(lambda_p = lambda_n * (1 + s))
  rn = g[j, ]$rn
  rp = g[j, ]$rp
  lambda_p = g[j, ]$lambda_p
  lambda_n = g[j, ]$lambda_n
  

  
    sim <- new(Simulation,seed = 1, save_snapshot = F)
    sim$duplicate_internal_cells <- T
    sim$update_tissue("Liver", 2000, 2000)
    sim$add_mutant(name = "A", epigenetic_rates = c(`+-` = rn, 
                                                    `-+` = rp), growth_rates = c(`+` = lambda_p, 
                                                                                 `-` = lambda_n), death_rates = c(`+` = 0, `-` = 0))
    sim$place_cell("A-", 1000, 1000)
    sim$run_up_to_size("A+", 10000)
    n_w <- n_h <- 50
    bbox <- sim$search_sample(c(`A+` = 50, `A-` = 50), 
                              n_w, n_h)
    
    sim$sample_cells("Sampling", bbox$lower_corner, 
                     bbox$upper_corner)
    
    forest <- sim$get_samples_forest()
`
and to me work on mac. But when i run it as in the second moment to run a job on Orfeo i got the floating point exception, for instance at j = 3, k =1, seed = 1.  
I never got the error unexpected symbol in:
"                  bbox$upper_corner)
                forest <- sim$get_samples_forest()."
Execution halted

**Comment by riccardobergamin** [comment] 2024-03-13 11:39
probably because there is the dot "." at the end? That is my mistake.

**Comment by albertocasagrande** [comment] 2024-03-13 13:39
The last code is syntactically correct, but it does not raise any issues.

**Comment by riccardobergamin** [comment] 2024-03-13 14:49
even on Orfeo/Linux?

**Comment by albertocasagrande** [comment] 2024-03-14 08:50
No error under Linux for the last code.

The code in the zip file that you posted above misses the script `EASYPAR_LSF_Run.R` and the file `EASYPAR_LSF_input_jobarray.csv` as well. 

Can you provide a **full and syntactically correct** minimal example to reproduce the error?

**Comment by riccardobergamin** [comment] 2024-03-15 08:47
yes ,sure.
[alberto 2.zip](https://github.com/caravagnalab/rRACES/files/14613049/alberto.2.zip)

**Comment by albertocasagrande** [comment] 2024-05-06 11:33
I could not execute the above code. I am closing the issue because there is no minimal example reproducing the problem.

**Closed by albertocasagrande** 2024-05-06 11:33 UTC
